// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwikxlahhmjypjlrrdkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3aWt4bGFoaG1qeXBqbHJyZGtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTUyMTgsImV4cCI6MjA1Nzg5MTIxOH0.-b9va7NqOalKIRNH9zgH7QEdJJpOyq4aCYtSEGa8IfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);